# Generated by Django 3.2 on 2021-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
