# Generated by Django 3.2 on 2021-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210504_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
